In [3]:
#program 1: calculate total weekly energy from a list
daily_kwh=[400,450,500,550,600,650,700,750,800]
total_energy=sum(daily_kwh)
print("total_energy Used",total_energy,"KWH")

total_energy Used 5400 KWH

In [4]:
building_usage = {
    "CSE": 700,
    "HOSTEL": 140
}
print("HOSTEL used: ", building_usage["HOSTEL"], "KWH")

HOSTEL used:  140 KWH

In [5]:
# Program 3: A Function to calculate electricity cost
def calculate_bill(kwh,rate_per_unit):
    return kwh * rate_per_unit

today_bill = calculate_bill(600,8)
print("Today's estimated bill is Rs.", today_bill)

Today's estimated bill is Rs. 4800

In [7]:
# program 4: Read a file line by line
with open("campus_energy.csv", "r") as file:
   for line in file.readlines():
      print(line.strip())

﻿DATE,BUILDING,KWH_USED,PEAK_HOUR_USAGE
05-10-2026,CSE,400,100
06-10-2026,HOSTEL,450,114
07-10-2026,CSE,500,121
08-10-2026,CIVIL,550,110
09-10-2026,HOSTEL,600,140
10-10-2026,MANAGEMENT,650,110
11-10-2026,CSE,700,130
12-10-2026,CIVIL,750,120
13-10-2026,HOSTEL,800,111

In [13]:
# program 5:import the panda as library
import pandas as pd
df=pd.read_csv("campus_energy.csv")
print("Here is the raw data:")
display(df.head())
building_totals = df.groupby('BUILDING')['KWH_USED'].sum()
print("\ntotal usage per building:")
print(building_totals)
print("\nstatical summary:")
display(df.describe())

Here is the raw data:

         DATE BUILDING  KWH_USED  PEAK_HOUR_USAGE
0  05-10-2026      CSE       400              100
1  06-10-2026   HOSTEL       450              114
2  07-10-2026      CSE       500              121
3  08-10-2026    CIVIL       550              110
4  09-10-2026   HOSTEL       600              140

total usage per building:
BUILDING
CIVIL         1300
CSE           1600
HOSTEL        1850
MANAGEMENT     650
Name: KWH_USED, dtype: int64

statical summary:

         KWH_USED  PEAK_HOUR_USAGE
count    9.000000         9.000000
mean   600.000000       117.333333
std    136.930639        12.010412
min    400.000000       100.000000
25%    500.000000       110.000000
50%    600.000000       114.000000
75%    700.000000       121.000000
max    800.000000       140.000000

In [14]:
with open("README_md", "w")as file:
  file.write("# campus Energy project\n")
  file.write("This repository contain my week 1 hand-on python and pandas.\n")
  file.write("Create by: [akash]")
  print("README.md has successfully created")

README.md has successfully created